git pull debaditya master
git commit -m "pull2"
git pull piyush master
git commit -m "pull2"
git pull kunwar master
git commit -m "pull2"
git pull mohit master
git commit -m "pull2"
git pull rishabh master
git commit -m "pull2"
git pull rohan master
git commit -m "pull2"
git pull sanjana master
git commit -m "pull2"
git pull shikhar master
git commit -m "pull2"
git pull sujith master
git commit -m "pull2"
git pull suneha master
git commit -m "pull2"